import { getRunOptions, repoPath, toPosixRelative, writeTextFile } from './lib/io.js';
import { loadInferenceMappingModel } from './lib/inference_mapping.js';

const OUTPUT_FILE = repoPath('library', 'taxonomy', 'generated', 'relations.generated.ts');

function toTypeScriptModule(model: Awaited<ReturnType<typeof loadInferenceMappingModel>>): string {
  const rows = model.relations;
  return [
    '/* eslint-disable */',
    '// Auto-generated by technical/scripts/generate_inference_relations.ts',
    '',
    'export interface IsSubtopicRow {',
    '  subtopic: string;',
    '  parentTopic: string;',
    '}',
    '',
    'export interface TopicMappingRow {',
    '  topic: string;',
    '  addresses: string[];',
    '}',
    '',
    'export interface StatutoryViolationRow {',
    '  actionReference: string;',
    '  statutoryReference: string;',
    '}',
    '',
    `export const isSubtopics: IsSubtopicRow[] = ${JSON.stringify(rows.isSubtopics, null, 2)};`,
    '',
    `export const topicMappings: TopicMappingRow[] = ${JSON.stringify(rows.topicMappings, null, 2)};`,
    '',
    `export const statutoryViolations: StatutoryViolationRow[] = ${JSON.stringify(rows.statutoryViolations, null, 2)};`,
    ''
  ].join('\n');
}

async function main(): Promise<void> {
  const options = getRunOptions(process.argv.slice(2));
  const model = await loadInferenceMappingModel();
  const content = toTypeScriptModule(model);
  const result = await writeTextFile(OUTPUT_FILE, content, options);

  if (options.check) {
    if (result.changed) {
      console.error(`Would update ${toPosixRelative(OUTPUT_FILE)}`);
      process.exit(1);
    }
    console.log('generate_inference_relations.ts check passed.');
    return;
  }

  const status = result.changed ? 'Updated' : 'No changes';
  console.log(
    `${status} ${toPosixRelative(OUTPUT_FILE)} (isSubtopics=${model.relations.isSubtopics.length}, topicMappings=${model.relations.topicMappings.length}, statutoryViolations=${model.relations.statutoryViolations.length})`
  );
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
